name: Release pipeline

on:
  push:
    branches:
      - main
      - "feature/**"
      - "feat/**"
      - "hotfix/**"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.14.0'
      - uses: pnpm/action-setup@v2
        with:
          version: 7.9.0
      - name: Install deps
        run: pnpm i --frozen-lockfile
      - name: Run linter
        run: pnpm run lint
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.14.0'
      - uses: pnpm/action-setup@v2
        with:
          version: 7.9.0
      - name: Install deps
        run: pnpm i --frozen-lockfile
      - name: Run tests
        run: pnpm test
      - name: Run storybook build
        run: pnpm build-storybook
  build-and-deploy:
    name: Build, Deploy to GitHub pages, Release npm package
    needs: [linting, tests]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Trigger release process only on main
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.14.0'
      - uses: pnpm/action-setup@v2
        with:
          version: 7.9.0
      - name: 🛠 Install & Build
        run: |
          pnpm i --frozen-lockfile
          pnpm build-storybook
          pnpm build-package
      - name: 🚀 Release npm package
        uses: cycjimmy/semantic-release-action@v3
        with:
          extra_plugins: |
            @semantic-release/git
          branches: |
            [
              'main'
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: 📃 Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: github-pages
          folder: storybook-static
          target-folder: docs